name: CI Build
on:
  push:
    branches:
      - 'main'

env:
  BUILD_TYPE: 'Release'  
  CHOCO_CONFIG_DIR: 'build/chocolatey'
  CHOCO_PACKAGE_OUTPUT_DIR: 'choco-package'
  # CHOCO_PACKAGE_REPO_INTERNAL: ''
  # CHOCO_PACKAGE_REPO_PUBLIC: ''
  PUBLISHED_PROJECT_FILE: 'src/SampleChocoConsoleApp/Microsoft.SampleChocoConsoleApp.csproj'
  CHOCO_PACKAGE_REPO_FOLDER: 'chocolatey-packages'
  CHOCO_SRC_DIR: 'choco-src'
  CODE_COVERAGE_THRESHOLD: 0
  DOTNET_VERSION: '3.1.200'
  OUTPUT_DIR: 'dist'    
  
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout from default branch        
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore project dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration ${{ env.BUILD_TYPE }}

      - name: Publish the CLI project for Chocolatey
        run: dotnet publish ${{ env.PUBLISHED_PROJECT_FILE }} -r win-x64 -o ./${{ env.OUTPUT_DIR }}/${{ env.CHOCO_SRC_DIR }} --configuration ${{ env.BUILD_TYPE }}  -p:PublishTrimmed=true

      - name: Create the Chocolatey packages
        shell: bash
        run: |
          mkdir ./${{ env.OUTPUT_DIR }}/${{ env.CHOCO_PACKAGE_OUTPUT_DIR }}

          find ./${{ env.CHOCO_CONFIG_DIR }} -name "*.nuspec" |
          while read f
          do
            choco pack $f --outputdirectory ./${{ env.OUTPUT_DIR }}/${{ env.CHOCO_PACKAGE_OUTPUT_DIR }}
          done

   
#      - name: Push the Chocolatey package        
#        shell: bash
#        run: | 
#          find ./${{ env.OUTPUT_DIR }}/${{ env.CHOCO_PACKAGE_OUTPUT_DIR }}/ -name "*.nupkg" |
#          while read f; do            
#            choco push $f -s ${{ env.CHOCO_PACKAGE_REPO_PUBLIC }} -k ${{ secrets.CHOCO_PUBLIC_REPO_TOKEN }}
#          done